name: Deploy service

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cert
      run: |
        echo "${{ secrets.SERVER }}"
        nslookup "${{ secrets.SERVER }}"

    - name: Install cert
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -p 8822 -H ${{ secrets.SERVER }} >> ~/.ssh/known_hosts
    
    - name: Подключение к серверу и обновление контейнера
      run: |
        ssh -p 8822 -i ~/.ssh/deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER }} << 'EOF'
          docker run -d \
            --name myaws \
            --restart=always \
            -e GPT_API_KEY=${{ secrets.GPT_API_KEY }} \
            -e TELEGRAM_API_TOKEN=${{ secrets.TELEGRAM_API_TOKEN }} \
            -v ${{ secrets.HOST_DB_PATH }}/telegram_bot.sqlite \
            eevarn/k8sphp
        EOF
