name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: DockerHub login
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:0.0.2
    - name: Upload image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot:0.0.2
